### ISSUE TITLE
Option to specify width

### ISSUE THREAD

**Issue by racinmat** [kimikage/ProfileSVG.jl#33]
It would be great to have option to set different width https://github.com/kimikage/ProfileSVG.jl/blob/master/src/ProfileSVG.jl#L80 currently flamegraphs I create have very weird sizes of 1000x2905, which on one hand takes lots of space vertically, and makes me unable to use lots of space on my monitor vertically.

**Comment by kimikage** [comment]
I'm going to support `width` and `height` options as part of #8. (Currently writing the tests and docs.)

Manual `height` can cause cropping, so I plan to add support for `maxdepth` option and #17 after that.
