### ISSUE TITLE
Improve the experience of zoom-in zoom-out

### ISSUE THREAD

**Issue by findmyway** [kimikage/ProfileSVG.jl#5]
When trying to zoom-in or zoom-out with wheel-up/down, the whole page also scrolls up/down in the meantime. 

(I'm a novice to js, not sure if it's possible to do so)

**Comment by timholy** [comment]
I'm certainly not the one to fix this. See the note on the README about this package needing a maintainer.

**Comment by kimikage** [comment]
I can't reproduce this issue (on Chrome and Firefox on Windows 10). What environment do you use to view the SVG?

Incidentally, I don't think the zoom-in-zoom-out UI experience is pretty good. I want to zoom centered on the mouse cursor position. I also want the touch interface.

**Comment by findmyway** [comment]
Hmmm, I'm using this package on Win10 with Chrome in the Jupyter notebook.

**Comment by timholy** [comment]
Worth remembering that the README directs users to ProfileVega as an alternative.

**Comment by kimikage** [comment]
I have not identified the cause yet. However, the current event handlers are obsolete and non-standard.
https://github.com/kimikage/ProfileSVG.jl/blob/8ea09a8dce3879f8675bb121fbbde102e0d879bf/src/svgwriter.jl#L133-L139

- `attachEvent` was used in IE 8.  No need to support it anymore. (IE 8 does not support the SVG!)
- The current standard wheel event is `WheelEvent` (`"wheel"`). The event has the `deltaY` property.
   - Perhaps only iOS Safari doesn't support `WheelEvent`. Touch UI support is required separately.

I guess we also need `stopPropagation`.

**Comment by kimikage** [comment]
I still cannot reproduce this issue on Chrome. On the other hand, a similar bug occurred on IE11 and old Edge, even though I modernized the event handler.
For the IE and Edge cases, we will probably reduce the glitch by setting the event handler on the parent `<svg>` element instead of the `<g>` element.

**Edit:**
@findmyway, if it's not too much trouble, please let me know the result of PR #18.

**Comment by findmyway** [comment]
I just tried #18 , it works very well now! 🎉 🎉 🎉 

By the way, I'm using Chromium Version 84.0.4118.0 (Official Build) (64-bit)

**Comment by kimikage** [comment]
Thank you for the report. I'm going to merge and release PRs step by step. Please wait a moment for the tag release.
