### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by timholy** [kimikage/ProfileSVG.jl#52]
https://discourse.julialang.org/t/saving-profile-data/51173 led me to this:

```julia
julia> using RegistryCompatTools

julia> held_back_by("FlameGraphs")
2-element Vector{String}:
 "ProfileSVG"
 "ProfileVega"
```

**Comment by kimikage** [comment]
Yeah, I also wanted to release v0.2 soon. However, as my contribution chart shows, I can't find the time these days. :tired_face:
I would like to apply some planned changes and show the release schedule over this weekend.

**Comment by timholy** [comment]
Understood, and I feel likewise!

**Comment by kimikage** [comment]
cf. https://github.com/kimikage/ProfileSVG.jl/pull/53#issuecomment-742104964

**Comment by kimikage** [comment]
cf. #54

**Comment by kimikage** [comment]
ProfileSVG v0.2.0 was released! :tada:

https://discourse.julialang.org/t/ann-profilesvg-v0-2-0/51657
